name: Unity - Request manual activation file
on:
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Correct action name:
      - name: Request activation file (.alf)
        uses: game-ci/unity-request-activation-file@v2

      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation-file
          path: Unity_v*.alf
