name: Unity License Request (one-time)
on:
  workflow_dispatch:

jobs:
  request-alf:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v4
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation-file
          path: Unity_v*.alf
