name: Build & Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ secrets.UNITY_LICENSE != '' }}  # <-- skip build if license not set
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-WebGL-
            Library-

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          allowDirtyBuild: true
          buildName: WebGLBuild
          buildsPath: build
          # projectPath: .   # uncomment if your Unity project is in a subfolder

      - name: Show build output
        run: |
          echo "==== ls -R build ===="
          ls -R build || true

      - name: Find publish directory
        id: find
        shell: bash
        run: |
          set -euo pipefail
          CANDIDATES=$(find build -type f -name index.html | sort || true)
          PUBLISH_DIR=""
          while IFS= read -r f; do
            d="$(dirname "$f")"
            if [ -d "$d/TemplateData" ]; then
              PUBLISH_DIR="$d"
              break
            fi
          done <<< "$CANDIDATES"
          if [ -z "$PUBLISH_DIR" ]; then
            echo "No publishable WebGL folder (index.html + TemplateData) found under build/."
            echo "$CANDIDATES"
            exit 1
          fi
          echo "publish_dir=$PUBLISH_DIR" >> "$GITHUB_OUTPUT"
          echo "Publish dir: $PUBLISH_DIR"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.find.outputs.publish_dir }}

      - name: Return Unity License
        if: always()
        uses: game-ci/unity-return-license@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  deploy:
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
